### ISSUE TITLE
Result comes from cache

### ISSUE THREAD

**Issue by pratikkamani** [magepal/magento2-geoip#1]
I have used this.
Please check Below code. I have try to get customer country code on footer.phtml. And added this code to block. How can I get this code out of a cache?

Issue: currently all visitor get the same county due to load this block from the cache.

`namespace Rokanthemes\Themeoption\Block;
    class Themeoption extends \Magento\Framework\View\Element\Template 
    {
        public $geoIpService;

        public function __construct(
            \MagePal\GeoIp\Service\GeoIpService $geoIpService,
            array $data = []
        ) {
            $this->geoIpService = $geoIpService;
            parent::__construct($context, $data);

        }
        public function ipCountry()
        {
            return $this->geoIpService->getCountry();
        }
    }`

**Comment by srenon** [comment]
@pratikkamani ... that will not work because on first-page load the entire page will be cached.

My country redirect extension is 90% finished, so let me know if you are interested in purchasing and I will finish it.

What version of Magento are you using?

**Comment by pratikkamani** [comment]
Magento 2.3.0.
Block is cached and this is an issue.

**Comment by pratikkamani** [comment]
Actually, I am fetching customer country ID on theme footer.phtml.
And in the different county the country code display same. that's the reason due to a cache of pages.

**Comment by srenon** [comment]
You will need to use JavaScript

**Comment by pratikkamani** [comment]
Get country code is php code.
I don't think this is not solution.
Can you please explain your answer.

Thanks.

**Comment by srenon** [comment]
Take a look at how Magento handle user data... see https://github.com/magepal/magento2-google-tag-manager/blob/master/CustomerData/JsDataLayer.php or create your own ajax call/controller to get this info.
